### ISSUE TITLE
Java 8 support?

### ISSUE THREAD

**Issue by Niko-sk2x** [Obsidian-StudiosInc/os-xtoo#70]
I understand if java 8 support is not going to happen, but I thought it wouldn't hurt to ask. If it's not possible, I just have to stay on normal gentoo repositories.

I know this doesn't support java 8 and there are no packages in here that strictly need it. But I really find gentoo's java support to be a bit lacking and considering switching to this. But I need java 8 and probably also java 10 (can't 11+, for now).

This is probably very unusual, but I'm making (and also using, sometimes) Minecraft mods, and using gentoo as my main OS. The current state is, that anything newer than java 8 just doesn't work with it, and even with the latest work in progress version, only versions up to java 10 currently work. This game is also in an unusual situation, that people regularly use legacy versions of it, even 5 years old versions. And because of the nature of this system, large changes required to support newer versions of java usually aren't possible without breaking backwards compatibility. The current version that requires java 8 only is also likely to stay mostly supported around for at least the next year, and used by players and servers probably for the next 5+ years.

**Comment by wltjr** [comment]
It is to much work to try to support the legacy Java 8. Plus ever since introduction of the ```-source``` and ```-target``` options, building Java on Gentoo for anything other than the current JVM is [broken](https://wiki.gentoo.org/wiki/Java_Developer_Guide#Bootstrap_class_path). You need older rt.jars to build on anything less than the current JVM, which has never been done on Gentoo and the eclasses and tooling have no support for adding an older rt.jar to bootclasspath, or anything for bootclasspath. This was fixed in Java 9+ with the new ```--release```, which does not require older rt.jar to safely build code for older JVM. This overlay uses ```--release``` only and it is to much work to try to switch between the two, plus other differences. Thus it is only 9+, really 10+. If you build anything on Gentoo using say Java 10-11, but run under Java 8, you will have issues due to broken linking from missing bootclasspath rt.jar for Java 8 or other. Its been known issue for sometime, just few ever run into that as they tend to use the same JDK they used for building. But if you build with newer, and run under older, you will have issues.

I have kept a openjdk=bin:10 ebuild in the overaly for those who need 10. Though Oracle pulled their 10 release and recommends 11 over 10. I understand the various issues with moving to 11, mostly in updated code, and/or classpaths. Bit more complicated if using JavaFX. That could likely be restored if you needed that, oracle-jdk-bin:10. Just have to grab jar from Oracle archives and restore that symlink, and digest.

Java 8 I hope does not become like Python 2.7, never going away, people choosing to stick to that and never move forward. The entire problem Java core developers were trying to address is the legacy dependency. People need to start updating their code and moving things forward. I have touched many packages, and updating is not that much work in most cases. The longer Java 8 is supported and people can run that, the longer it will remain around. Another reason why I rather not bother with Java 8 and focus on the future of Java, and hopefully get others to update their code bases and supporter newer JDK not just older.  Just like I would love to see the day Python 2.7 goes away and is no longer required. To many things still require that, though I mostly have it gone on servers. For the same reasons people do not move past Java 8, people are stuck on Python 2.7. Legacy versions need to die!

Java in Gentoo has been neglected for over a decade. Its decline started when I [resigned as a developer in 2008](https://bugs.gentoo.org/135927#c11). A few have furthered it for a period of time, but never fully addressed the situation. I am [permanently banned](https://bugs.gentoo.org/640160#c12) from Gentoo communities. That is semi moot as it is easier for me to avoid Gentoo bureaucracy and politics and work freely here. Though I know many do not benefit from my work, lots of updated packages, all that can build and work with latest JDK. The matter is entirely Gentoo's making. I tried to return numerous times to clean up the massive mess. They are assuming someone else will come along, and they never have nor will they. Thus Java on Gentoo will likely continue to suffer till who knows when. There are not many more experienced with Java on Gentoo than myself, and clearly most Gentoo devs want nothing to do with me. I fail to see how it will ever improve, I waited many years. That is why I just replaced the entire mess.

Anyway if you are able to use this overlay and have issues let me know and I will do my best to address them ASAP.

**Comment by Niko-sk2x** [comment]
In that case, thanks for the reply, but I'm not going to be able to use this probably for the next few years.

To explain why java 8 is required here (even binaries are fine, I don't need it built from source. And I dont need it as a system VM either): MinecraftForge (this is pretty much the only reason I even use java.) for 1.12 will never be compatible with anything above java 8 (and I have seen, mostly unsuccessful, attempts to make it work anyway) and I need that. It's dealing with bytecode, complex classloading, and, by necessity, abuses some parts of java in a way that won't with with newer versions. In later versions, a lot of the code has been rewritten (because it's known that once project valhalla comes out, it will become necessary anyway) but java 11 still doesn't work. The code has been updated to move on. But old versions continue to need support (again, because of the slightly unique situation of minecraft), and they can't be made to work with new java.


If I can find binary packages of openjdk 8, I may just extract it somewhere and keep it out of portage, and use this overlay anyway, because is looks really nice.

**Comment by wltjr** [comment]
You can get binaries of OpenJDK 8 from [AdoptOpenJDK](https://adoptopenjdk.net/) or from [Oracle](https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html). If you just need the JDK/JRE then you likely need not bother with this overlay.

This overlay is for if you need updated Java packages, and/or want to use JDK 11+ for building Java packages or applications. That is what you cannot do in tree, and why one would want this overlay, either for latest packages, and/or building with latest JDK.

Otherwise the tree stuff should suffice for 8. I believe they have an openjdk 8 ebuild now from source, plus IcedTea, and maybe still Oracle JDK 8.

If you do use this overlay and try to get minecraft or other stuff running under Java 11+ and have issues. You are welcome to report them as issues. I may or may not be able to resolve, but it would be interesting to see what the issues are. Really short of like JavaFX usage and/or changes in classes, it should run via some means. May have to add extra stuff to classpath and/or use special flags when running. I really haven't seen anything that is bound to an older JDK, surely not at the binary level. Most issues arise in building, and can require change to build under JDK 11. I haven't anything at this time that can build under older but not newer, same for running. Though I am sure there is stuff out there that would require older and/or have issues under newer.

**Comment by Niko-sk2x** [comment]
> If you do use this overlay and try to get minecraft or other stuff running under Java 11+ and have issues. You are welcome to report them as issues. I may or may not be able to resolve, but it would be interesting to see what the issues are.

Latest versions will probably work once updated to ASM7.

The issues that exist in 1.12 cannot be reasonably solved by anything other than a rewrite of large sections of this. Just one of the issues is LaunchWrapper: https://github.com/Mojang/LegacyLauncher which handles bytecode transformation, along with some things related to handling launch arguments. There are too many things that rely on details of how it works. And then there are things like this  `public static <T extends Enum<? >> T addEnum(Class<T> enumType, String enumName, Class<?>[] paramTypes, Object... paramValues)`

**Comment by wltjr** [comment]
> Latest versions will probably work once updated to ASM7.

I still have ASM slotted, but I cannot recall having to fix any packages for ASM updates. I guess they need code changes for ASM7. Though worse case I can restore a asm:6 slot.

> The issues that exist in 1.12 cannot be reasonably solved by anything other than a rewrite of large sections of this. Just one of the issues is LaunchWrapper: https://github.com/Mojang/LegacyLauncher 

I will have to see what the issues there are.

>And then there are things like this `public static <T extends Enum<? >> T addEnum(Class<T> enumType, String enumName, Class<?>[] paramTypes, Object... paramValues)`

That is the sort of thing I patch. I have run into that a fair amount, only in a few cases could I not resolve the issue. Those are usually changes to Java's generics handling.

**Comment by Niko-sk2x** [comment]
Minecraft (especially modded) will never fit into any repositories. Not portage, not debian repositories, nowhere. It'ss a standalone thing. It includes all the libraries it ships in it's own directory structure in `$HOME`. A lot of this can't be patched because again, this is with mods, and a lot of weird stuff is in public API. 

So the libraries I have on my system have absolutely zero correlation with what MC uses. All that really matters is the JVM.  And that's all I really need. Also just to clear it up, modding is in all ways possible unofficial here. This does not come from Mojang.

But I also use a fair but of other java software that doesn't work this way.
